### ISSUE TITLE
Unable to run inference

### ISSUE THREAD

**Issue by vinayakarannil** [princewang1994/TextSnake.pytorch#27]
i am getting below error when i try to test pretrained model on my image

=============End=============
Loading from ./save/pretrained/textsnake_vgg_180.pth
Start testing TextSnake.
Traceback (most recent call last):
  File "demo.py", line 110, in <module>
    main()
  File "demo.py", line 92, in main
    inference(detector, test_loader, output_dir)
  File "demo.py", line 46, in inference
    contours, output = detector.detect(image)
  File "/home/ec2-user/vinayak/TextSnake.pytorch/util/detection.py", line 239, in detect
    tr_pred = output[0, 0:2].softmax(dim=0).data.cpu().numpy()
AttributeError: 'Tensor' object has no attribute 'softmax'

**Comment by vinayakarannil** [comment]
I think my pytorch version was the problem. I was using 0.4.0.

I have upgraded to 0.4.1 and now it works. Closing the issue

Regards
