### ISSUE TITLE
About CTW1500 and ICDAR2015 dataset

### ISSUE THREAD

**Issue by rookiecm** [princewang1994/TextSnake.pytorch#30]
Hi, thank you for your open source contributions.
I follow total_text.py write the data loading part of CTW 1500 and encountered the following problems
`
Traceback (most recent call last):
  File "CTW1500_debug.py", line 86, in <module>
    img, train_mask, tr_mask, tcl_mask, radius_map, sin_map, cos_map, meta = trainset[idx]
  File "CTW1500_debug.py", line 55, in __getitem__
    return self.get_training_data(image, polygons, image_id=image_id, image_path=image_path)
  File "/work3/liuchao/TextSnake.pytorch/dataset/dataload.py", line 179, in get_training_data
    sideline1, sideline2, center_points, radius = polygon.disk_cover(n_disk=cfg.n_disk)
  File "/work3/liuchao/TextSnake.pytorch/dataset/dataload.py", line 53, in disk_cover
    inner_points2 = split_edge_seqence(self.points, self.e2, n_disk)
  File "/work3/liuchao/TextSnake.pytorch/util/misc.py", line 195, in split_edge_seqence
    while(cur_end > point_cumsum[cur_node + 1]):
IndexError: index 1 is out of bounds for axis 0 with size 1
`
some of the cases have the above problems. I can understand the reason of the error, but I don't know how to correct it. Can you help me fix the bug or share your CTW1500 and ICDAR 2015 dataset file? Thank you very much.

**Comment by lijun20** [comment]
have you solved it ?

**Comment by lifei1229** [comment]
hello, I also met the question these days, have you solved it ? @lijun20 @rookiecm @princewang1994 

> have you solved it ?

**Comment by Bovey0809** [comment]
I found the same error.
