### ISSUE TITLE
Error using torch.load to load textsnake_vgg_0.pth downloaded from Google Drive using Google Colab (to get free GPU)

### ISSUE THREAD

**Issue by NoAchache** [princewang1994/TextSnake.pytorch#43]
Hello,

torch.load does not manage to load correctly textsnake_vgg_0.pth (downloaded with google drive) using google colab which is linked to my drive. Here is the command I ran:

! python3.6 train_textsnake.py example --viz --batch_size 8 --resume /content/gdrive/My\ Drive/Colab\ Notebooks/TextSnake.pytorch/save/synthtext_pretrain/textsnake_vgg_0.pth

Here is the error I get (straight after it printed all the configs): 

Loading from /content/gdrive/My Drive/Colab Notebooks/TextSnake.pytorch/save/synthtext_pretrain/textsnake_vgg_0.pth
Traceback (most recent call last):
  File "train_textsnake.py", line 238, in <module>
    main()
  File "train_textsnake.py", line 210, in main
    load_model(model, cfg.resume)
  File "train_textsnake.py", line 46, in load_model
    state_dict = torch.load(model_path)['state_dict']
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 454, in _load
    return legacy_load(f)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 380, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/usr/lib/python3.6/tarfile.py", line 1589, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1619, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1482, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.6/tarfile.py", line 2297, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.6/tarfile.py", line 1092, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
OSError: [Errno 5] Input/output error

I assume part of the error is that pytorch is trying to open as a tar file although it is not.

I would really appreciate your help.

Best Wishes.

**Comment by NoAchache** [comment]
I am talking about the line  state_dict = torch.load(model_path)  of the function  def load_model(model, model_path):   of the file train_textsnake.py.

**Comment by NoAchache** [comment]
I tried to run it locally on my computer (with CPU) and loading the model works fine (but not the training part due to a lack of RAM). Apparently the 'OSError: [Errno 5] Input/output error' often happen on google colab for large files (20 gb or more from what I read). It still does not really make sense since the .pth file is much smaller than that.

**Comment by NoAchache** [comment]
It worked by uploading directly the file to google colab instead of loading it from google drive using:

```
from google.colab import files
uploaded= files.upload()
```
