### ISSUE TITLE
can icdar2015 dataset be used in this modle?

### ISSUE THREAD

**Issue by Jackandrome** [princewang1994/TextSnake.pytorch#6]
does the total_text.py can only deal with curved texts ?

**Comment by princevandev** [comment]
Yes, code in total_text.py assumes that gt are given with polygon(x0, y0, x1, y1..., xn, yn) format, so icdar(rectangle text annotation) can be used if you treat annotations as a quadrangles(x0, y0, x1, y1, x2, y2, x3, y3).

**Comment by Jackandrome** [comment]
thank you for your response 
I don't really use pytorch,so when I'm running your code, I got this error:
DataLoader worker (pid 1008) exited unexpectedly with exit code 1.

so I can't load data,eventhough  I changed the batch size into 1 , could you help me with that?

**Comment by princevandev** [comment]
@Jackandrome  can you provide the exact error output and the full exception track stack?

**Comment by Jackandrome** [comment]
@princewang1994 

-`Traceback (most recent call last):
  File "train.py", line 158, in <module>
    main()
  File "train.py", line 144, in main
    train(model, train_loader, criterion, scheduler, optimizer, epoch)
  File "train.py", line 51, in train
    output = model(img)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fuzilong/TextSnake/network/textnet.py", line 40, in forward
    C1, C2, C3, C4, C5 = self.backbone(x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fuzilong/TextSnake/network/vgg.py", line 17, in forward
    C1 = self.stage1(x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 227, in handler
    _error_if_any_worker_fails()


RuntimeError: DataLoader worker (pid 4322) is killed by signal: Bus error. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.
`


**If i let the num_worker= 0 , there is no error ,but  the data loading is very slow.**

**Comment by princevandev** [comment]
Sorry I cannot reproduce this error, but someone else met the same error on [this issue](https://github.com/pytorch/pytorch/issues/8976). May using the same python environment or pytorch version will help you.
